apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: support-prod
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'ticket-service'
        static_configs:
          - targets: ['ticket-service:5001']
      - job_name: 'support-service'
        static_configs:
          - targets: ['support-service:5002']
      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:5003']
      - job_name: 'reporting-service'
        static_configs:
          - targets: ['reporting-service:5004']
