server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/tickets {
        proxy_pass http://ticket-service:5001;
    }

    location /api/support {
        proxy_pass http://support-service:5002;
    }

    location /api/notifications {
        proxy_pass http://notification-service:5003;
    }

    location /api/reports {
        proxy_pass http://reporting-service:5004;
    }
}